# Generated by Django 3.2.23 on 2025-02-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0002_auto_20250213_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstation',
            old_name='retail_price',
            new_name='price',
        ),
    ]
