# Generated by Django 3.2.23 on 2025-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0003_rename_retail_price_fuelstation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
