# Generated by Django 3.2.23 on 2025-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0004_auto_20250213_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
